### ISSUE TITLE
s390x/tcg: Implement Vector-Enhancements Facility 2 for s390x

### ISSUE THREAD

**Issue by edelsohn** [edelsohn/qemu#2]
This is a proxy for https://gitlab.com/qemu-project/qemu/-/issues/738

The emulation part of QEMU (currently TCG) for the s390x architecture lacks some facilities that were introduced with Z15 and used by GCC and LLVM with -march=z15. The goal of this request is to implement the Vector-Enhancements Facility 2 for the s390x tcg frontend so that s390x user and softmmu targets will be able to handle code containing instructions of that facility.

**Comment by vibhuti019** [comment]
I wish to work on this issue, can you guide me a bit?

**Comment by vibhuti019** [comment]
@edelsohn I would like to work on this issue. Please guide me a bit about it.

**Comment by pabrams** [comment]
Someone commenting on the gitlab issue claimed a month ago to have finished it, yet the gitlab issue, and proxies such as this, remain open?

**Comment by vibhuti019** [comment]
@pabrams that is why I had question and there were no PRs related to this issue

**Comment by edelsohn** [comment]
The Gitlab issue remains open because QEMU has been in a freeze and the patch could not be committed.

**Comment by dmiller423** [comment]
[It should be resolved now](https://gitlab.com/thuth/qemu/-/commits/s390x-next/)

**Comment by edelsohn** [comment]
Issue closed in Gitlab so reflecting here.
